//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class catEstados
    {
        public catEstados()
        {
            this.catDistritos = new HashSet<catDistritos>();
            this.catMunicipios = new HashSet<catMunicipios>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string claveINEGI { get; set; }
    
        public virtual ICollection<catDistritos> catDistritos { get; set; }
        public virtual ICollection<catMunicipios> catMunicipios { get; set; }
    }
}
