//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class catFiguras
    {
        public catFiguras()
        {
            this.tbExpedActPersonas = new HashSet<tbExpedActPersonas>();
            this.tbExpedPersonas = new HashSet<tbExpedPersonas>();
        }
    
        public int id { get; set; }
        public string figura { get; set; }
        public Nullable<bool> actuacion { get; set; }
        public Nullable<System.DateTime> C_fechaReg { get; set; }
    
        public virtual ICollection<tbExpedActPersonas> tbExpedActPersonas { get; set; }
        public virtual ICollection<tbExpedPersonas> tbExpedPersonas { get; set; }
    }
}
