//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class catLocalidades
    {
        public catLocalidades()
        {
            this.tbDatosDomicilios = new HashSet<tbDatosDomicilios>();
            this.tbDomicilioAsunto = new HashSet<tbDomicilioAsunto>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string claveINEGI { get; set; }
        public Nullable<int> idMunicipio { get; set; }
    
        public virtual catMunicipios catMunicipios { get; set; }
        public virtual ICollection<tbDatosDomicilios> tbDatosDomicilios { get; set; }
        public virtual ICollection<tbDomicilioAsunto> tbDomicilioAsunto { get; set; }
    }
}
