//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class catSubTipoDeAsunto
    {
        public catSubTipoDeAsunto()
        {
            this.catSTAOpciones = new HashSet<catSTAOpciones>();
            this.tbExpedActSTAsuntoDetalle = new HashSet<tbExpedActSTAsuntoDetalle>();
        }
    
        public int id { get; set; }
        public int idTipoAsunto { get; set; }
        public string subTipo { get; set; }
        public System.DateTime C_fechaReg { get; set; }
    
        public virtual ICollection<catSTAOpciones> catSTAOpciones { get; set; }
        public virtual catTipoDeAsunto catTipoDeAsunto { get; set; }
        public virtual ICollection<tbExpedActSTAsuntoDetalle> tbExpedActSTAsuntoDetalle { get; set; }
    }
}
