//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class catTipoDeAsunto
    {
        public catTipoDeAsunto()
        {
            this.catSubTipoDeAsunto = new HashSet<catSubTipoDeAsunto>();
            this.tbExpedActuaciones = new HashSet<tbExpedActuaciones>();
            this.tbExpedientes = new HashSet<tbExpedientes>();
        }
    
        public int id { get; set; }
        public string tipo { get; set; }
        public Nullable<int> idOrgAreaJuridica { get; set; }
        public System.DateTime C_fechaReg { get; set; }
    
        public virtual ICollection<catSubTipoDeAsunto> catSubTipoDeAsunto { get; set; }
        public virtual ICollection<tbExpedActuaciones> tbExpedActuaciones { get; set; }
        public virtual tbOrganismos tbOrganismos { get; set; }
        public virtual ICollection<tbExpedientes> tbExpedientes { get; set; }
    }
}
