//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class catUbicacionFisica
    {
        public catUbicacionFisica()
        {
            this.tbExpedientes = new HashSet<tbExpedientes>();
        }
    
        public int id { get; set; }
        public string ubicacion { get; set; }
        public Nullable<System.DateTime> C_fechaReg { get; set; }
    
        public virtual ICollection<tbExpedientes> tbExpedientes { get; set; }
    }
}
