//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico
    {
        public int id { get; set; }
        public int idAccionRealizada { get; set; }
        public System.DateTime fechaYhora { get; set; }
        public string tabla { get; set; }
        public string idRegistro { get; set; }
        public string cambiosRealizados { get; set; }
        public string usuario { get; set; }
        public System.DateTime C_fechaRegistro { get; set; }
    
        public virtual HistoricoAcciones HistoricoAcciones { get; set; }
    }
}
