//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoAcciones
    {
        public HistoricoAcciones()
        {
            this.Historico = new HashSet<Historico>();
        }
    
        public int id { get; set; }
        public string accion { get; set; }
        public Nullable<System.DateTime> C_fechaRegistro { get; set; }
    
        public virtual ICollection<Historico> Historico { get; set; }
    }
}
