//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class BDJuridicoEntities : DbContext
    {
        public BDJuridicoEntities()
            : base("name=BDJuridicoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbExpedActuaciones> tbExpedActuaciones { get; set; }
        public DbSet<tbExpedActPersonas> tbExpedActPersonas { get; set; }
        public DbSet<tbArchivos> tbArchivos { get; set; }
        public DbSet<tbExpedArchivos> tbExpedArchivos { get; set; }
        public DbSet<cat_EtiquetaTermino> cat_EtiquetaTermino { get; set; }
        public DbSet<cat_Paises> cat_Paises { get; set; }
        public DbSet<catActuaciones> catActuaciones { get; set; }
        public DbSet<catDistritos> catDistritos { get; set; }
        public DbSet<catEjercicios> catEjercicios { get; set; }
        public DbSet<catEstados> catEstados { get; set; }
        public DbSet<catFiguras> catFiguras { get; set; }
        public DbSet<catHechos> catHechos { get; set; }
        public DbSet<catLocalidades> catLocalidades { get; set; }
        public DbSet<catMunicipios> catMunicipios { get; set; }
        public DbSet<catSTAOpciones> catSTAOpciones { get; set; }
        public DbSet<catSubTipoDeAsunto> catSubTipoDeAsunto { get; set; }
        public DbSet<catTerminos> catTerminos { get; set; }
        public DbSet<catTipoDeDocumento> catTipoDeDocumento { get; set; }
        public DbSet<catTipoRecepcionDocumento> catTipoRecepcionDocumento { get; set; }
        public DbSet<catUbicacionFisica> catUbicacionFisica { get; set; }
        public DbSet<tbDatosDomicilios> tbDatosDomicilios { get; set; }
        public DbSet<tbDatosSociales> tbDatosSociales { get; set; }
        public DbSet<tbDomicilioAsunto> tbDomicilioAsunto { get; set; }
        public DbSet<tbEASTADOpciones> tbEASTADOpciones { get; set; }
        public DbSet<tbExpedActExtraAsunto> tbExpedActExtraAsunto { get; set; }
        public DbSet<catTipoDeAsunto> catTipoDeAsunto { get; set; }
        public DbSet<catDelegaciones> catDelegaciones { get; set; }
        public DbSet<catDiasInhabiles> catDiasInhabiles { get; set; }
        public DbSet<catGruposDePersonas> catGruposDePersonas { get; set; }
        public DbSet<tbOrganismos> tbOrganismos { get; set; }
        public DbSet<Historico> Historico { get; set; }
        public DbSet<HistoricoAcciones> HistoricoAcciones { get; set; }
        public DbSet<tbDatosLaborales> tbDatosLaborales { get; set; }
        public DbSet<tbDatosSistema> tbDatosSistema { get; set; }
        public DbSet<tbExpedActDocumentos> tbExpedActDocumentos { get; set; }
        public DbSet<tbExpedActSTAsuntoDetalle> tbExpedActSTAsuntoDetalle { get; set; }
        public DbSet<tbExpedientes> tbExpedientes { get; set; }
        public DbSet<tbExpedPersonas> tbExpedPersonas { get; set; }
        public DbSet<tbPersonas> tbPersonas { get; set; }
        public DbSet<vDetalleAsuntosExpediente> vDetalleAsuntosExpediente { get; set; }
        public DbSet<vDetalleDocumentos> vDetalleDocumentos { get; set; }
        public DbSet<vExpedientesResumido> vExpedientesResumido { get; set; }
        public DbSet<vw_DetalleDocumentosExp> vw_DetalleDocumentosExp { get; set; }
        public DbSet<vw_tcpersonal> vw_tcpersonal { get; set; }
        public DbSet<vw_UsuariosLexus> vw_UsuariosLexus { get; set; }
    
        public virtual ObjectResult<sp_DetalleDocumentoExp_Result> sp_DetalleDocumentoExp(string numDoc_Asunto, Nullable<int> tipofecha, string fechaInicial, string fechaFinal)
        {
            var numDoc_AsuntoParameter = numDoc_Asunto != null ?
                new ObjectParameter("NumDoc_Asunto", numDoc_Asunto) :
                new ObjectParameter("NumDoc_Asunto", typeof(string));
    
            var tipofechaParameter = tipofecha.HasValue ?
                new ObjectParameter("tipofecha", tipofecha) :
                new ObjectParameter("tipofecha", typeof(int));
    
            var fechaInicialParameter = fechaInicial != null ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(string));
    
            var fechaFinalParameter = fechaFinal != null ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DetalleDocumentoExp_Result>("sp_DetalleDocumentoExp", numDoc_AsuntoParameter, tipofechaParameter, fechaInicialParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<string> SP_FOLIO_DOCUMENTO(Nullable<int> idDocumento, string siglasArea)
        {
            var idDocumentoParameter = idDocumento.HasValue ?
                new ObjectParameter("idDocumento", idDocumento) :
                new ObjectParameter("idDocumento", typeof(int));
    
            var siglasAreaParameter = siglasArea != null ?
                new ObjectParameter("siglasArea", siglasArea) :
                new ObjectParameter("siglasArea", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_FOLIO_DOCUMENTO", idDocumentoParameter, siglasAreaParameter);
        }
    }
}
