//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbArchivos
    {
        public tbArchivos()
        {
            this.tbExpedArchivos = new HashSet<tbExpedArchivos>();
            this.tbExpedActDocumentos = new HashSet<tbExpedActDocumentos>();
        }
    
        public System.Guid id { get; set; }
        public string nombre { get; set; }
        public string idUnicoSistema { get; set; }
        public string extension { get; set; }
        public Nullable<decimal> tamano { get; set; }
        public byte[] bytesArchivo { get; set; }
        public Nullable<System.DateTime> C_fechaReg { get; set; }
    
        public virtual ICollection<tbExpedArchivos> tbExpedArchivos { get; set; }
        public virtual ICollection<tbExpedActDocumentos> tbExpedActDocumentos { get; set; }
    }
}
