//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDatosSociales
    {
        public int id { get; set; }
        public Nullable<int> idPersona { get; set; }
        public Nullable<bool> sexo { get; set; }
        public Nullable<int> edad { get; set; }
        public Nullable<bool> migrante { get; set; }
        public Nullable<int> idPais { get; set; }
        public Nullable<bool> indigena { get; set; }
        public string etnia { get; set; }
        public Nullable<bool> periodista { get; set; }
        public string agenciaPeriodistica { get; set; }
        public Nullable<System.DateTime> C_fechaRegistro { get; set; }
        public Nullable<bool> C_regActivo { get; set; }
    
        public virtual cat_Paises cat_Paises { get; set; }
        public virtual tbPersonas tbPersonas { get; set; }
    }
}
