//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDatosLaborales
    {
        public int id { get; set; }
        public Nullable<int> idPersona { get; set; }
        public Nullable<int> idOrganismo { get; set; }
        public string lugar { get; set; }
        public Nullable<int> idtcPersonalSSP { get; set; }
        public Nullable<System.DateTime> C_fechaReg { get; set; }
        public Nullable<bool> C_regActivo { get; set; }
    
        public virtual tbOrganismos tbOrganismos { get; set; }
        public virtual tbPersonas tbPersonas { get; set; }
    }
}
