//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEASTADOpciones
    {
        public int idSTAOpcion { get; set; }
        public int idExAcSTDetalle { get; set; }
        public string valorTexto { get; set; }
        public Nullable<decimal> valorNumero { get; set; }
        public System.DateTime C_fechaReg { get; set; }
    
        public virtual catSTAOpciones catSTAOpciones { get; set; }
        public virtual tbExpedActSTAsuntoDetalle tbExpedActSTAsuntoDetalle { get; set; }
    }
}
