//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbExpedActSTAsuntoDetalle
    {
        public tbExpedActSTAsuntoDetalle()
        {
            this.tbEASTADOpciones = new HashSet<tbEASTADOpciones>();
        }
    
        public int id { get; set; }
        public int idSubTipo { get; set; }
        public int idActuacion { get; set; }
        public System.DateTime fecha { get; set; }
        public string opcionOtro { get; set; }
        public System.DateTime C_fechaReg { get; set; }
    
        public virtual catSubTipoDeAsunto catSubTipoDeAsunto { get; set; }
        public virtual ICollection<tbEASTADOpciones> tbEASTADOpciones { get; set; }
        public virtual tbExpedActuaciones tbExpedActuaciones { get; set; }
    }
}
