//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbExpedientes
    {
        public tbExpedientes()
        {
            this.tbExpedActuaciones = new HashSet<tbExpedActuaciones>();
            this.tbExpedArchivos = new HashSet<tbExpedArchivos>();
            this.tbExpedPersonas = new HashSet<tbExpedPersonas>();
        }
    
        public System.Guid id { get; set; }
        public string numero { get; set; }
        public string numeroInterno { get; set; }
        public Nullable<System.DateTime> fechaYhoraRecibido { get; set; }
        public Nullable<System.DateTime> fechaTermino { get; set; }
        public Nullable<int> idTipoAsunto { get; set; }
        public string asunto { get; set; }
        public Nullable<int> idOrganismoOrigen { get; set; }
        public Nullable<int> idOrganismoDestino { get; set; }
        public Nullable<int> idEjercicio { get; set; }
        public Nullable<int> idUbicacionFisica { get; set; }
        public Nullable<int> idDomicilioAsunto { get; set; }
        public Nullable<int> idDistrito { get; set; }
        public Nullable<int> idDelegacion { get; set; }
        public Nullable<int> idHechos { get; set; }
        public Nullable<System.DateTime> C_fechaReg { get; set; }
        public Nullable<int> idTermino { get; set; }
        public Nullable<int> idAreaJuridica { get; set; }
    
        public virtual catDistritos catDistritos { get; set; }
        public virtual catEjercicios catEjercicios { get; set; }
        public virtual catHechos catHechos { get; set; }
        public virtual catTerminos catTerminos { get; set; }
        public virtual catTipoDeAsunto catTipoDeAsunto { get; set; }
        public virtual catUbicacionFisica catUbicacionFisica { get; set; }
        public virtual tbDomicilioAsunto tbDomicilioAsunto { get; set; }
        public virtual ICollection<tbExpedActuaciones> tbExpedActuaciones { get; set; }
        public virtual ICollection<tbExpedArchivos> tbExpedArchivos { get; set; }
        public virtual tbOrganismos tbOrganismos { get; set; }
        public virtual tbOrganismos tbOrganismos1 { get; set; }
        public virtual tbOrganismos tbOrganismos2 { get; set; }
        public virtual ICollection<tbExpedPersonas> tbExpedPersonas { get; set; }
    }
}
