//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbExpedActuaciones
    {
        public tbExpedActuaciones()
        {
            this.tbExpedActPersonas = new HashSet<tbExpedActPersonas>();
            this.tbExpedActDocumentos = new HashSet<tbExpedActDocumentos>();
            this.tbExpedActSTAsuntoDetalle = new HashSet<tbExpedActSTAsuntoDetalle>();
        }
    
        public int id { get; set; }
        public Nullable<System.Guid> idExpediente { get; set; }
        public Nullable<int> idActuacion { get; set; }
        public Nullable<int> idOrganismoDestino { get; set; }
        public string accion { get; set; }
        public Nullable<System.DateTime> fechaTermino { get; set; }
        public Nullable<System.DateTime> C_fechaReg { get; set; }
        public Nullable<bool> C_regActivo { get; set; }
        public Nullable<int> idOrganismoOrigen { get; set; }
        public Nullable<int> idAreaJuridica { get; set; }
        public Nullable<int> idTipoAsunto { get; set; }
        public Nullable<int> IdSubAreaJuridica { get; set; }
    
        public virtual ICollection<tbExpedActPersonas> tbExpedActPersonas { get; set; }
        public virtual catActuaciones catActuaciones { get; set; }
        public virtual tbExpedActExtraAsunto tbExpedActExtraAsunto { get; set; }
        public virtual catTipoDeAsunto catTipoDeAsunto { get; set; }
        public virtual tbOrganismos tbOrganismos { get; set; }
        public virtual tbOrganismos tbOrganismos1 { get; set; }
        public virtual tbOrganismos tbOrganismos2 { get; set; }
        public virtual tbOrganismos tbOrganismos3 { get; set; }
        public virtual ICollection<tbExpedActDocumentos> tbExpedActDocumentos { get; set; }
        public virtual ICollection<tbExpedActSTAsuntoDetalle> tbExpedActSTAsuntoDetalle { get; set; }
        public virtual tbExpedientes tbExpedientes { get; set; }
    }
}
