//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbExpedActDocumentos
    {
        public int id { get; set; }
        public Nullable<int> idExpedActuaciones { get; set; }
        public string numeroDocumento { get; set; }
        public Nullable<System.DateTime> fechaDocumento { get; set; }
        public Nullable<System.DateTime> fechaRecepcion { get; set; }
        public string asunto { get; set; }
        public string notas { get; set; }
        public Nullable<int> idTipoDeDocumento { get; set; }
        public Nullable<int> idTipoRecepcionDocumento { get; set; }
        public Nullable<System.Guid> idArchivo { get; set; }
        public Nullable<bool> esPrincipal { get; set; }
        public Nullable<System.DateTime> C_fechaReg { get; set; }
        public string folio_doc { get; set; }
    
        public virtual catTipoDeDocumento catTipoDeDocumento { get; set; }
        public virtual catTipoRecepcionDocumento catTipoRecepcionDocumento { get; set; }
        public virtual tbArchivos tbArchivos { get; set; }
        public virtual tbExpedActuaciones tbExpedActuaciones { get; set; }
    }
}
