//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbExpedPersonas
    {
        public int id { get; set; }
        public Nullable<System.Guid> idExpediente { get; set; }
        public Nullable<int> idPersona { get; set; }
        public Nullable<int> idFigura { get; set; }
        public Nullable<int> idGrupoPersona { get; set; }
        public Nullable<System.DateTime> C_fechaReg { get; set; }
    
        public virtual catFiguras catFiguras { get; set; }
        public virtual catGruposDePersonas catGruposDePersonas { get; set; }
        public virtual tbExpedientes tbExpedientes { get; set; }
        public virtual tbPersonas tbPersonas { get; set; }
    }
}
