//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOrganismos
    {
        public tbOrganismos()
        {
            this.catTipoDeAsunto = new HashSet<catTipoDeAsunto>();
            this.tbExpedActuaciones = new HashSet<tbExpedActuaciones>();
            this.tbExpedActuaciones1 = new HashSet<tbExpedActuaciones>();
            this.tbExpedActuaciones2 = new HashSet<tbExpedActuaciones>();
            this.tbExpedActuaciones3 = new HashSet<tbExpedActuaciones>();
            this.tbDatosLaborales = new HashSet<tbDatosLaborales>();
            this.tbDatosSistema = new HashSet<tbDatosSistema>();
            this.tbExpedientes = new HashSet<tbExpedientes>();
            this.tbExpedientes1 = new HashSet<tbExpedientes>();
            this.tbExpedientes2 = new HashSet<tbExpedientes>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> nivel { get; set; }
        public string jerarquia { get; set; }
        public Nullable<System.DateTime> C_fechaRegistro { get; set; }
    
        public virtual ICollection<catTipoDeAsunto> catTipoDeAsunto { get; set; }
        public virtual ICollection<tbExpedActuaciones> tbExpedActuaciones { get; set; }
        public virtual ICollection<tbExpedActuaciones> tbExpedActuaciones1 { get; set; }
        public virtual ICollection<tbExpedActuaciones> tbExpedActuaciones2 { get; set; }
        public virtual ICollection<tbExpedActuaciones> tbExpedActuaciones3 { get; set; }
        public virtual ICollection<tbDatosLaborales> tbDatosLaborales { get; set; }
        public virtual ICollection<tbDatosSistema> tbDatosSistema { get; set; }
        public virtual ICollection<tbExpedientes> tbExpedientes { get; set; }
        public virtual ICollection<tbExpedientes> tbExpedientes1 { get; set; }
        public virtual ICollection<tbExpedientes> tbExpedientes2 { get; set; }
    }
}
