//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPersonas
    {
        public tbPersonas()
        {
            this.tbDatosDomicilios = new HashSet<tbDatosDomicilios>();
            this.tbDatosLaborales = new HashSet<tbDatosLaborales>();
            this.tbDatosSistema = new HashSet<tbDatosSistema>();
            this.tbDatosSociales = new HashSet<tbDatosSociales>();
            this.tbExpedActPersonas = new HashSet<tbExpedActPersonas>();
            this.tbExpedPersonas = new HashSet<tbExpedPersonas>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public Nullable<bool> clasificacion { get; set; }
        public Nullable<System.DateTime> C_fechaReg { get; set; }
        public Nullable<bool> C_regActivo { get; set; }
        public string nombreCompleto { get; set; }
    
        public virtual ICollection<tbDatosDomicilios> tbDatosDomicilios { get; set; }
        public virtual ICollection<tbDatosLaborales> tbDatosLaborales { get; set; }
        public virtual ICollection<tbDatosSistema> tbDatosSistema { get; set; }
        public virtual ICollection<tbDatosSociales> tbDatosSociales { get; set; }
        public virtual ICollection<tbExpedActPersonas> tbExpedActPersonas { get; set; }
        public virtual ICollection<tbExpedPersonas> tbExpedPersonas { get; set; }
    }
}
