//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDetalleAsuntosExpediente
    {
        public int idOpcion { get; set; }
        public int idExAcSTDetalle { get; set; }
        public string textoOpcion { get; set; }
        public bool esNumeroOpcion { get; set; }
        public string valorTexto { get; set; }
        public Nullable<decimal> valorNumero { get; set; }
        public Nullable<int> idSubTipo { get; set; }
        public string subTipoAsunto { get; set; }
        public string otroSubTipoAsunto { get; set; }
        public int idEASTADetalle { get; set; }
        public System.DateTime fechaEASTADetalle { get; set; }
        public int idExpedActuacion { get; set; }
        public Nullable<System.Guid> idExpediente { get; set; }
        public Nullable<int> idTipoActuacion { get; set; }
        public string tipoActuacion { get; set; }
        public Nullable<int> idTipoAsunto { get; set; }
        public string tipoAsunto { get; set; }
        public string otroTipoAsunto { get; set; }
        public Nullable<int> idOrgAreaJuridica { get; set; }
    }
}
