//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vExpedientesResumido
    {
        public System.Guid id { get; set; }
        public string numero { get; set; }
        public Nullable<int> idActuacion { get; set; }
        public string actuacion { get; set; }
        public Nullable<bool> regActivoActuacion { get; set; }
        public Nullable<int> idOrganismoDestino { get; set; }
        public string Destino { get; set; }
        public Nullable<System.DateTime> fechaTermino { get; set; }
    }
}
