//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DetalleDocumentosExp
    {
        public int id { get; set; }
        public string numeroDocumento { get; set; }
        public Nullable<System.DateTime> fechaDocumento { get; set; }
        public Nullable<System.DateTime> fechaRecepcion { get; set; }
        public string asunto { get; set; }
        public Nullable<System.DateTime> C_fechaReg { get; set; }
        public int idExpedActuacion { get; set; }
        public Nullable<System.Guid> idExpediente { get; set; }
        public Nullable<int> idActuacion { get; set; }
        public int idOrgOrigen { get; set; }
        public string nombreOrgOrigen { get; set; }
        public int idOrgDestino { get; set; }
        public string nombreOrgDestino { get; set; }
        public int idOrgAreaJuridica { get; set; }
        public string nombreOrgAreaJuridica { get; set; }
        public Nullable<System.DateTime> fechaTermino { get; set; }
        public Nullable<System.DateTime> fechaRegActuacion { get; set; }
        public string tipo { get; set; }
        public string numero { get; set; }
    }
}
