//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_tcpersonal
    {
        public int idtcpersonal { get; set; }
        public int idtcentidadfederativa { get; set; }
        public int idtcmunicipio { get; set; }
        public string rfc { get; set; }
        public string curp { get; set; }
        public string paterno { get; set; }
        public string materno { get; set; }
        public string nombre { get; set; }
        public string noimss { get; set; }
        public string nosnm { get; set; }
        public string folioife { get; set; }
        public string estadocivil { get; set; }
        public string lugarnacimiento { get; set; }
        public string localidad { get; set; }
        public string genero { get; set; }
        public System.DateTime fechanacimiento { get; set; }
        public Nullable<int> sidepol { get; set; }
        public int marcabaja { get; set; }
        public System.DateTime dt_tcpersonal { get; set; }
        public string afndeclaracionpatrimonial { get; set; }
        public string afnantecedentespenales { get; set; }
        public string telefonorecados { get; set; }
        public string email { get; set; }
        public string celular { get; set; }
        public string telefono { get; set; }
        public int idtcgradoestudio { get; set; }
    }
}
