//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexus2._0.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UsuariosLexus
    {
        public string TIPO_USUARIO { get; set; }
        public string ROL { get; set; }
        public string NOMBRECOMPLETO { get; set; }
        public string LOGIN { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string OFICINA { get; set; }
        public string ESTATUS { get; set; }
        public System.DateTime ÚLTIMO_ACCESO { get; set; }
        public string SISTEMA { get; set; }
    }
}
